---author: "cesar"
date: "2023-01-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(ggplot2)

library(tidyverse)
library(caret)
library(doParallel)
```

```{r}
players_read <- read.csv("fut_bin21_players.csv")
normalize <- function(x){
 (x - min(x)) / (max(x) - min(x))
}
```
```{r}
players <- players_read[players_read$league != "Icons",]
xbox_vec <- c("xbox_last","xbox_max", "xbox_min", "xbox_prp")
pc_vec <- c("pc_last","pc_max", "pc_min", "pc_prp", "ps4_max", "ps4_min")
player_unused_cols <- c("futbin_id","date_of_birth","origin","added_date", "base_id", "resource_id", xbox_vec, pc_vec, "ps4_prp", "specialities", "traits")
players <- players[,!names(players)%in%player_unused_cols]

keepers <- players[players$position=="GK",]
line <- players %>% filter(position!="GK")

```
```{r}
keeper_unused_cols <- c("pace", "dribbling", "passing","defending", "shooting", "physicality", "cb", "rb",
             "lb", "rwb", "lwb", "cdm","cm","rm", "lm", "cm", "cam", "cf", "rf", "lf", "rw", "lw", "st")
keepers <- keepers[,!names(keepers)%in%keeper_unused_cols]
```

```{r}
ggplot(finalVals, aes(x=value, color=type)) + 
  geom_boxplot()
```
```{r}
clust_county <- keepers[complete.cases(keepers),] %>% select("ps4_last")

# use elbow chart to find best number of centers for kmeans
explained_variance = function(data_in, k){
  # Running the kmeans algorithm.
  set.seed(1)
  kmeans_obj = kmeans(data_in, centers = k, algorithm = "Lloyd", iter.max = 30)
  
  # Variance accounted for by clusters:
  # var_exp = intercluster variance / total variance
  var_exp = kmeans_obj$betweenss / kmeans_obj$totss
  var_exp  
}

explained_var_county = sapply(1:10, explained_variance, data_in = clust_county) #removing variables that won't be used for cluster

elbow_data_county = data.frame(k = 1:10, explained_var_county)

# Plotting data.
ggplot(elbow_data_county, 
       aes(x = k,  
           y = explained_var_county)) + 
  geom_point(size = 4) +           #<- sets the size of the data points
  geom_line(size = 1) +            #<- sets the thickness of the line
  xlab('k') + 
  ylab('Inter-cluster Variance / Total Variance') + 
  theme_light()
```
```{r echo=FALSE, results=FALSE, warning=FALSE, message=FALSE}
clust_county <- keepers[complete.cases(keepers),] %>% select("ps4_last")

# 4 centers was found to be the best
set.seed(1)
kmeans_obj_county = kmeans(clust_county, centers = 3, 
                        algorithm = "Lloyd")   #<- there are several ways of implementing

kmeans_obj_county

kmeans_obj_county$cluster

# create column for cluster assignment
county_cluster_data <- cbind(keepers[complete.cases(keepers),], clusterNum = kmeans_obj_county$cluster)

# breakup the datset into their respective cluster datasets
cluster_1_data <- filter(county_cluster_data, clusterNum == 1) 
cluster_2_data <- filter(county_cluster_data, clusterNum == 2) 
cluster_3_data <- filter(county_cluster_data, clusterNum == 3) 
```
```{r}
nrow(cluster_1_data)
```

```{r}

```